# Generated by Django 4.1.4 on 2022-12-12 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='eConnectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_Nombre', models.CharField(max_length=100)),
                ('apellido_Nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('dirección', models.CharField(max_length=150)),
                ('código_zip', models.CharField(max_length=150)),
                ('teléfono', models.CharField(max_length=10)),
                ('web', models.URLField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.IntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagens/')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Evento_fecha', models.DateTimeField()),
                ('Descripción', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('Asistentes', models.ManyToManyField(blank=True, to='app.econnectuser')),
                ('Lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lugar')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
